//! `govctl init` - scaffold the governance stack into a directory.

use crate::templates;
use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

/// Scaffold the seven governance files plus `.govctlignore` and `.govctl/manifest.toml`.
///
/// Three modes (see D006):
///   * default - refuse if any target file already exists.
///   * `force` - overwrite everything.
///   * `merge` - add only the files that are missing; never touch existing ones. This is how you
///     adopt govctl on a project that already has a partial stack.
pub fn run(
    path: &Path,
    project_name: Option<&str>,
    force: bool,
    merge: bool,
    dry_run: bool,
) -> Result<()> {
    let project = resolve_project_name(path, project_name);
    let date = today_iso();

    let mut planned: Vec<(PathBuf, String)> = Vec::new();
    for t in templates::TEMPLATES {
        planned.push((
            path.join(t.filename),
            templates::render(t.body, &project, &date),
        ));
    }
    planned.push((path.join(".govctlignore"), templates::GOVCTLIGNORE.to_string()));
    planned.push((
        path.join(".govctl").join("manifest.toml"),
        manifest(&project, &date),
    ));

    let rel = |p: &Path| {
        p.strip_prefix(path)
            .unwrap_or(p)
            .to_string_lossy()
            .into_owned()
    };

    // MERGE: add only missing files; leave existing ones untouched.
    if merge {
        let missing: Vec<&(PathBuf, String)> = planned.iter().filter(|(p, _)| !p.exists()).collect();
        let present: Vec<String> = planned
            .iter()
            .filter(|(p, _)| p.exists())
            .map(|(p, _)| rel(p))
            .collect();

        if dry_run {
            println!("govctl init --merge (dry run) into {}:", path.display());
            for (p, _) in &missing {
                println!("  + would add  {}", rel(p));
            }
            for f in &present {
                println!("  = keep       {f}");
            }
            return Ok(());
        }

        if missing.is_empty() {
            println!("govctl init --merge: nothing to add; all {} files already present.", planned.len());
            return Ok(());
        }

        fs::create_dir_all(path).with_context(|| format!("creating {}", path.display()))?;
        for (p, body) in &missing {
            if let Some(parent) = p.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(p, body).with_context(|| format!("writing {}", p.display()))?;
        }

        println!("govctl init --merge - added {} missing file(s) to {}", missing.len(), path.display());
        for (p, _) in &missing {
            println!("  + {}", rel(p));
        }
        for f in &present {
            println!("  = kept (unchanged) {f}");
        }
        println!("\nNext: run `govctl validate .` to check for drift.");
        return Ok(());
    }

    // DEFAULT: refuse to clobber unless --force.
    if !force {
        let existing: Vec<String> = planned
            .iter()
            .filter(|(p, _)| p.exists())
            .map(|(p, _)| rel(p))
            .collect();
        if !existing.is_empty() {
            anyhow::bail!(
                "refusing to overwrite existing files: {} (use --merge to add only missing files, or --force to overwrite)",
                existing.join(", ")
            );
        }
    }

    if dry_run {
        println!("govctl init (dry run) - would scaffold into {}:", path.display());
        for (p, _) in &planned {
            println!("  + {}", rel(p));
        }
        return Ok(());
    }

    fs::create_dir_all(path).with_context(|| format!("creating {}", path.display()))?;
    for (p, body) in &planned {
        if let Some(parent) = p.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(p, body).with_context(|| format!("writing {}", p.display()))?;
    }

    println!(
        "govctl init - scaffolded {} files into {}",
        planned.len(),
        path.display()
    );
    println!("  project: {project}");
    for (p, _) in &planned {
        println!("  + {}", rel(p));
    }
    println!("\nNext: edit DECISIONS.md, then run `govctl validate .` to check for drift.");
    Ok(())
}

fn resolve_project_name(path: &Path, explicit: Option<&str>) -> String {
    if let Some(name) = explicit {
        if !name.trim().is_empty() {
            return name.to_string();
        }
    }
    // Fall back to the directory name; resolve "." against the real cwd.
    let dir = if path.as_os_str() == "." || path.as_os_str().is_empty() {
        std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
    } else {
        path.to_path_buf()
    };
    dir.file_name()
        .and_then(|n| n.to_str())
        .filter(|s| !s.is_empty())
        .unwrap_or("project")
        .to_string()
}

fn manifest(project: &str, date: &str) -> String {
    format!(
        "# Generated by govctl init - do not edit by hand.\n\
         project_name = \"{project}\"\n\
         govctl_version = \"{}\"\n\
         created = \"{date}\"\n",
        env!("CARGO_PKG_VERSION")
    )
}

/// Today's date as `YYYY-MM-DD`, computed from the system clock with no external crate.
fn today_iso() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let (y, m, d) = civil_from_days((secs / 86_400) as i64);
    format!("{y:04}-{m:02}-{d:02}")
}

/// Convert a count of days since the Unix epoch into a `(year, month, day)` triple.
/// Howard Hinnant's `civil_from_days` algorithm - exact, no leap-year special-casing bugs.
fn civil_from_days(days_since_epoch: i64) -> (i64, u32, u32) {
    let z = days_since_epoch + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let m = (if mp < 10 { mp + 3 } else { mp - 9 }) as u32;
    (y + if m <= 2 { 1 } else { 0 }, m, d)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn civil_from_days_known_dates() {
        // 2026-06-03 is 20607 days after the Unix epoch.
        assert_eq!(civil_from_days(20_607), (2026, 6, 3));
        // Unix epoch itself.
        assert_eq!(civil_from_days(0), (1970, 1, 1));
        // Late-February date in a non-leap year.
        assert_eq!(civil_from_days(19_416), (2023, 2, 28));
    }

    #[test]
    fn manifest_contains_project_and_version() {
        let m = manifest("Acme", "2026-06-03");
        assert!(m.contains("project_name = \"Acme\""));
        assert!(m.contains("created = \"2026-06-03\""));
        assert!(m.contains("govctl_version"));
    }

    #[test]
    fn project_name_falls_back_to_dir() {
        let p = Path::new("/tmp/my-cool-project");
        assert_eq!(resolve_project_name(p, None), "my-cool-project");
        assert_eq!(resolve_project_name(p, Some("Explicit")), "Explicit");
    }
}
